# Generated by Django 4.2.5 on 2023-10-03 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b_date', models.DateField(default=datetime.datetime(2023, 10, 3, 9, 32, 10, 621610, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(upload_to='Actor/')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b_date', models.DateField(default=datetime.datetime(2023, 10, 3, 9, 32, 10, 621610, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(upload_to='Director/')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('r_date', models.DateField(default=datetime.datetime(2023, 10, 3, 9, 32, 10, 621610, tzinfo=datetime.timezone.utc))),
                ('actors', models.ManyToManyField(to='moviebase.actor')),
                ('directors', models.ManyToManyField(to='moviebase.director')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebase.gender'),
        ),
        migrations.AddField(
            model_name='actor',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebase.gender'),
        ),
    ]
