# Generated by Django 4.2.5 on 2023-10-03 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='b_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 11, 19, 8, 628759, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='director',
            name='b_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 11, 19, 8, 630758, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='r_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 11, 19, 8, 631758, tzinfo=datetime.timezone.utc)),
        ),
    ]
